### ISSUE TITLE
Cannot install toga in venv

### ISSUE THREAD

**Issue by Zynh0722** [Zynh0722/ProjectCodeName#16]
pip install --pre toga returns this output

```    ERROR: Command errored out with exit status 1:
     command: 'c:\users\nicholas.ludwig.msd.000\documents\github\projectcodename\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\nicholas.ludwig.MSD.000\\AppData\\Local\\Temp\\pip-install-qr3q3m1c\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\Users\\nicholas.ludwig.MSD.000\\AppData\\Local\\Temp\\pip-install-qr3q3m1c\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\nicholas.ludwig.MSD.000\AppData\Local\Temp\pip-install-qr3q3m1c\pythonnet\pip-egg-info'
         cwd: C:\Users\nicholas.ludwig.MSD.000\AppData\Local\Temp\pip-install-qr3q3m1c\pythonnet\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\nicholas.ludwig.MSD.000\AppData\Local\Temp\pip-install-qr3q3m1c\pythonnet\setup.py", line 18, in <module>
        from wheel import bdist_wheel
    ModuleNotFoundError: No module named 'wheel'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.```

**Comment by 1ethanhansen** [comment]
@Zynh0722 this is the same as #40 correct?

**Comment by Zynh0722** [comment]
> @Zynh0722 this is the same as #40 correct?

@1ethanhansen Yes, #40 probably should have been put here, as it's just a solution to this one

**Comment by nrgabrielsen** [comment]
Same as #40, solved.
